[package]
name = "sopho"
version = "0.1.0"
edition = "2021"
authors = ["Athul T R <athultr1997@gmail.com>"]
description = "Open-source analytics platform"
license = "AGPL-3.0"

[workspace]
members = [".", "migration"]

[dependencies]
axum = { version = "0.8.1", features = ["json"] }
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = {version = "0.1.18"}
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs", "cors", "trace"] }
tower-cookies = "0.11.0"
http = "1.3.1"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
http-body-util = "0.1.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.140"
schemars = { version = "1.2", features = ["derive"] }
rig-core = "0.32.0"
tuple-conv = "1.0.1"
sea-orm = { version = "1.1.19", features = [ "sqlx-mysql", "sqlx-sqlite", "sqlx-postgres", "runtime-async-std-native-tls", "macros", "debug-print"] }
dotenv = "0.15"
uuid = { version = "1.4", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = "0.12.15"
anyhow = "1.0.97"
getrandom = "0.3.2"
base64 = "0.22.1"
time = "0.3.47"
sqlx = { version = "0.8", features = [ "runtime-tokio" ] }
thiserror = "=2.0.12"
strum = { version = "0.27", features = ["derive"] }
rust_decimal = { version = "1.36", features = ["serde-with-str"] }
migration = { path = "migration" }
argon2 = "0.5.3"
password-hash = "0.5.0"
sha2 = "0.10"
hex = "0.4"
aes-gcm = "0.10.3"
indoc = "2.0.7"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
tokio-cron-scheduler = { version = "0.15.1", features = ["postgres_storage"] }
