version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/sopho
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
