//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ai_summary")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub entity_type: String,
    pub entity_id: Uuid,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub summarized_entity_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_prompt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_prompt_used: Option<String>,
    pub generated_at: Option<DateTimeWithTimeZone>,
    pub requested_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
