//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod ai_configuration;
pub mod ai_summary;
pub mod canvas;
pub mod cell;
pub mod configuration;
pub mod connection;
pub mod conversation;
pub mod conversation_message;
pub mod conversation_message_content;
pub mod dashboard;
pub mod notebook;
pub mod session;
pub mod suggested_question;
pub mod user;
