//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod canvas;
pub mod cell;
pub mod chart;
pub mod configuration;
pub mod connection;
pub mod dashboard;
pub mod notebook;
pub mod session;
pub mod user;
