//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::canvas::Entity as Canvas;
pub use super::cell::Entity as Cell;
pub use super::chart::Entity as Chart;
pub use super::connection::Entity as Connection;
pub use super::dashboard::Entity as Dashboard;
pub use super::notebook::Entity as Notebook;
pub use super::session::Entity as Session;
pub use super::user::Entity as User;
