export const API_ENDPOINTS = {
  AUTH: {
    CREATE_SESSION: "/api/v1/auth/session",
    GET_SESSION: "/api/v1/auth/session",
    DELETE_SESSION: "/api/v1/auth/session",
    GET_PROFILE_DETAILS: "/api/v1/auth/me",
    REFRESH_TOKEN: "/api/v1/auth/refresh",
  },
  CONNECTION: {
    CREATE: "/api/v1/connection",
    GET_ALL: "/api/v1/connection",
    GET_BY_ID: "/api/v1/connection/:id",
    UPDATE: "/api/v1/connection/:id",
    DELETE: "/api/v1/connection/:id",
    EXECUTE_QUERY: "/api/v1/connection/:id/execute-query",
  },
  NOTEBOOK: {
    CREATE: "/api/v1/notebook",
    GET_ALL: "/api/v1/notebook",
    GET_BY_ID: "/api/v1/notebook/:id",
    GET_BY_CANVAS_ID: "/api/v1/notebook/canvas/:canvas_id",
    GET_CELLS_BY_NOTEBOOK_ID: "/api/v1/notebook/:id/cells",
    UPDATE: "/api/v1/notebook/:id",
    DELETE: "/api/v1/notebook/:id",
  },
  CELL: {
    CREATE: "/api/v1/cell",
    GET_ALL: "/api/v1/cell",
    GET_BY_ID: "/api/v1/cell/:id",
    UPDATE: "/api/v1/cell/:id",
    DELETE: "/api/v1/cell/:id",
    EXECUTE: "/api/v1/cell/:id/execute",
    EXECUTE_PREVIEW: "/api/v1/cell/:id/execute-preview",
    REORDER: "/api/v1/cell/:id/reorder",
  },
  CANVAS: {
    CREATE: "/api/v1/canvas",
    GET_ALL: "/api/v1/canvas",
    GET_BY_ID: "/api/v1/canvas/:id",
    UPDATE: "/api/v1/canvas/:id",
    DELETE: "/api/v1/canvas/:id",
  },
  DASHBOARD: {
    GET_BY_ID: "/api/v1/dashboard/:id",
    GET_BY_CANVAS_ID: "/api/v1/dashboard/canvas/:canvas_id",
    UPDATE: "/api/v1/dashboard/:id",
  },
  SEARCH: {
    SEARCH: "/api/v1/search",
  },
  CONVERSATIONAL_ANALYTICS: {
    CREATE: "/api/v1/conversational_analytics",
    GET_ALL: "/api/v1/conversational_analytics",
    GET_BY_ID: "/api/v1/conversational_analytics/:conversation_id",
    UPDATE: "/api/v1/conversational_analytics/:conversation_id",
    DELETE: "/api/v1/conversational_analytics/:conversation_id",
    COMPLETION: "/api/v1/conversational_analytics/:conversation_id/completion",
    SUGGEST_NAME: "/api/v1/conversational_analytics/:conversation_id/suggest-name",
  },
  AI_CONFIGURATION: {
    GET: "/api/v1/ai_configuration",
    UPDATE: "/api/v1/ai_configuration",
    DELETE: "/api/v1/ai_configuration",
    TEST: "/api/v1/ai_configuration/test",
  },
};
