pub const LOGICAL_PLAN_HYPOTHESIS_GENERATION_ROUNDS: u32 = 2;
pub const DATA_CATALOG_BATCHES: u32 = 5;
pub const SCHEMA_LINKING_MAX_REFINE_ROUNDS: u32 = 3;
pub const SQL_GENERATION_ROUNDS: u32 = 40;
pub const HYPOTHESIS_GENERATION_CONCURRENCY: usize = 4;
pub const SEARCH_SPACE_REDUCTION_CONCURRENCY: usize = 6;
pub const DATA_PROFILING_CONCURRENCY: usize = 6;
